# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.7.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
df = pd.read_csv('d:/jupyter/datasets/Churn_Modelling.csv')
df.head()


RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
X = df.iloc[:, 3:-1].values
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [5]:
Y = df.iloc[:, -1]
Y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

### Encoding categorical data

Label Encoding the "Gender" column

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [7]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [8]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size=0.1, random_state=0)

### Feature Scaling

In [11]:
x_train[:5]

array([[1.0, 0.0, 0.0, 628, 1, 34, 4, 158741.43, 2, 1, 1, 126192.54],
       [1.0, 0.0, 0.0, 716, 0, 52, 7, 65971.61, 2, 1, 0, 14608.0],
       [1.0, 0.0, 0.0, 617, 1, 25, 1, 102585.88, 2, 1, 1, 115387.4],
       [1.0, 0.0, 0.0, 571, 0, 33, 9, 0.0, 2, 0, 1, 77519.62],
       [1.0, 0.0, 0.0, 697, 1, 32, 7, 175464.85, 3, 1, 0, 116442.42]],
      dtype=object)

In [12]:
x_test[:5]

array([[0.0, 1.0, 0.0, 597, 0, 35, 8, 131101.04, 1, 1, 1, 192852.67],
       [1.0, 0.0, 0.0, 523, 0, 40, 2, 102967.41, 1, 1, 0, 128702.1],
       [0.0, 0.0, 1.0, 706, 0, 42, 8, 95386.82, 1, 1, 1, 75732.25],
       [1.0, 0.0, 0.0, 788, 1, 32, 4, 112079.58, 1, 0, 0, 89368.59],
       [0.0, 1.0, 0.0, 706, 1, 38, 5, 163034.82, 2, 1, 1, 135662.17]],
      dtype=object)

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)


In [14]:
x_train[:5]

array([[ 0.99445979, -0.5756396 , -0.57478426, -0.23053642,  0.91166287,
        -0.46249623, -0.34302584,  1.31679919,  0.80873785,  0.64376017,
         0.97108454,  0.45151104],
       [ 0.99445979, -0.5756396 , -0.57478426,  0.67997496, -1.0968967 ,
         1.25804455,  0.69365399, -0.16721975,  0.80873785,  0.64376017,
        -1.02977646, -1.4892912 ],
       [ 0.99445979, -0.5756396 , -0.57478426, -0.34435035,  0.91166287,
        -1.32276662, -1.37970566,  0.41849088,  0.80873785,  0.64376017,
         0.97108454,  0.26357605],
       [ 0.99445979, -0.5756396 , -0.57478426, -0.82029948, -1.0968967 ,
        -0.55808183,  1.38477387, -1.22255347,  0.80873785, -1.55337352,
         0.97108454, -0.39506244],
       [ 0.99445979, -0.5756396 , -0.57478426,  0.48338727,  0.91166287,
        -0.65366743,  0.69365399,  1.58432016,  2.53353422,  0.64376017,
        -1.02977646,  0.28192613]])

In [15]:
x_test[:5]

array([[-1.00557107,  1.73719807, -0.57478426, -0.55128475, -1.0968967 ,
        -0.36691063,  1.03921393,  0.87464179, -0.91605851,  0.64376017,
         0.97108454,  1.61093805],
       [ 0.99445979, -0.5756396 , -0.57478426, -1.31694205, -1.0968967 ,
         0.11101736, -1.03414572,  0.42459414, -0.91605851,  0.64376017,
        -1.02977646,  0.4951601 ],
       [-1.00557107, -0.5756396 ,  1.73978322,  0.57650776, -1.0968967 ,
         0.30218856,  1.03921393,  0.30332906, -0.91605851,  0.64376017,
         0.97108454, -0.42615036],
       [ 0.99445979, -0.5756396 , -0.57478426,  1.42493882,  0.91166287,
        -0.65366743, -0.34302584,  0.57035957, -0.91605851, -1.55337352,
        -1.02977646, -0.18897199],
       [-1.00557107,  1.73719807, -0.57478426,  0.57650776,  0.91166287,
        -0.08015383,  0.00253411,  1.38547963,  0.80873785,  0.64376017,
         0.97108454,  0.61621736]])

## Part 2 - Building the ANN

### Initializing the ANN

In [16]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

### Adding the input layer and the first hidden layer

### Adding the second hidden layer

### Adding the output layer

In [17]:
ann_model = Sequential([
    Dense(6,activation='relu'),
    Dense(6, activation='relu'),
    Dense(1, activation='sigmoid')
])


In [18]:
# ann_model.summary()

## Part 3 - Training the ANN

### Compiling the ANN

In [19]:
ann_model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics = ['accuracy']
)

### Training the ANN on the Training set

In [20]:
ann_model.fit(x_train, y_train, batch_size=32, epochs=100, verbose=2)

Epoch 1/100
282/282 - 5s - loss: 0.5206 - accuracy: 0.7839 - 5s/epoch - 18ms/step
Epoch 2/100
282/282 - 1s - loss: 0.4616 - accuracy: 0.8014 - 1s/epoch - 4ms/step
Epoch 3/100
282/282 - 1s - loss: 0.4418 - accuracy: 0.8102 - 1s/epoch - 4ms/step
Epoch 4/100
282/282 - 1s - loss: 0.4290 - accuracy: 0.8136 - 1s/epoch - 4ms/step
Epoch 5/100
282/282 - 1s - loss: 0.4198 - accuracy: 0.8172 - 1s/epoch - 4ms/step
Epoch 6/100
282/282 - 1s - loss: 0.4127 - accuracy: 0.8187 - 1s/epoch - 4ms/step
Epoch 7/100
282/282 - 1s - loss: 0.4065 - accuracy: 0.8187 - 1s/epoch - 4ms/step
Epoch 8/100
282/282 - 1s - loss: 0.4008 - accuracy: 0.8207 - 1s/epoch - 4ms/step
Epoch 9/100
282/282 - 1s - loss: 0.3954 - accuracy: 0.8216 - 1s/epoch - 4ms/step
Epoch 10/100
282/282 - 1s - loss: 0.3887 - accuracy: 0.8283 - 1s/epoch - 4ms/step
Epoch 11/100
282/282 - 1s - loss: 0.3810 - accuracy: 0.8352 - 1s/epoch - 4ms/step
Epoch 12/100
282/282 - 1s - loss: 0.3726 - accuracy: 0.8419 - 1s/epoch - 4ms/step
Epoch 13/100
282/282 - 1

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

In [21]:
predicted = ann_model.predict(x_test)
predicted[:5]

array([[0.30005127],
       [0.36148494],
       [0.08340269],
       [0.07219324],
       [0.06253739]], dtype=float32)

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

In [22]:
print(ann_model.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])) > 0.5)

[[False]]


**Solution**

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [28]:
y_pred = ann_model.predict(x_test)
y_pred = (y_pred > 0.5)
y_pred[:5]


array([[False],
       [False],
       [False],
       [False],
       [False]])

### Making the Confusion Matrix